var keywords = [
"virtual reality",
"augmented reality",
"tablets",
"smartphones",
"smartwatches",
"internet of things",
"antennas",
"information retrieval",
"crowdsourcing",
"video games",
"collaborative game theory",
"chairs",
"spatial augmented reality",
"depth cameras",
"projection mapping",
"Kinect",
"Vive",
"Oculus Rift",
"optics",
"mode switching",
"Unity",
"iOS",
"Android",
"Mechanical Turk"
]
